### PR TITLE
Make Pashword async + Update Site visuals to accomodate

### PR DESCRIPTION
**Pull request by brocococonut**
I've also thrown in a couple minor changes.
Because Pashword is no longer synchronous, copying it to the clipboard directly doesn't really work due to how long it takes to generate.. So I've added a click handler to the pashword itself to copy it. It's an extra step/click for the user which isn't ideal. But that should be easily remedied when the extension is created as that can just use the clipboard write permission to write whenever it needs to.

I've also added a "generating" state for the create pashword button so there's some visual feadback now that the site no longer freezes. It makes the button disabled and sets its opacity to 50%.

### CODE REVIEW

**Comment by NayamAmarshe** [comment]
You forgot an await in front of generatePashword call

**Comment by brocococonut** [comment]
> You forgot an await in front of generatePashword call

Uhhh... This one? o.o
The code all works from what I've tested.. I can't see the vercel deployment details though
https://github.com/NayamAmarshe/pashword/pull/6/commits/a92575c8626c6a529aeb855712478e96da62a36d#diff-9274dd6fc8c651f20eadbacc7b1e731acd8953b378090acbacd2e5030817bc40R98

**Comment by NayamAmarshe** [comment]
> > You forgot an await in front of generatePashword call
> 
> Uhhh... This one? o.o The code all works from what I've tested.. I can't see the vercel deployment details though [a92575c#diff-9274dd6fc8c651f20eadbacc7b1e731acd8953b378090acbacd2e5030817bc40R98](https://github.com/NayamAmarshe/pashword/commit/a92575c8626c6a529aeb855712478e96da62a36d#diff-9274dd6fc8c651f20eadbacc7b1e731acd8953b378090acbacd2e5030817bc40R98)

Yes, it does run but it's not type-safe and it fails compilation because the type Promise<string> is being assigned to string.

**Comment by brocococonut** [comment]
Ohhhh, yup yup
I had changed that in the pashword file, but was testing something else at the time so mustve reverted the change. I'll fix that up
Strange that typescript didn't pick that up for me when I was updating things initially 🤔

**Comment by brocococonut** [comment]
Wait.. no, that's there 🤔
Could you post the logs from vercel? And maybe reference where you're meaning?
Because the pashword function has the return type `Promise<string>`, and there's an `await` in the TSX file. They're just split up across the two commits.

Unless, is vercel annoyed by it being over two commits?

**Comment by NayamAmarshe** [comment]
> Wait.. no, that's there 🤔 Could you post the logs from vercel? And maybe reference where you're meaning? Because the pashword function has the return type `Promise<string>`, and there's an `await` in the TSX file. They're just split up across the two commits.
> 
> Unless, is vercel annoyed by it being over two commits?

This is the error:
Type `Promise<string> is not assignable to `string`:
> 52 |       pashedPassword = generatePashword(

**Comment by NayamAmarshe** [comment]
I'll test it locally and see what it's about. Also have a few things to add before pushing into production :)

**Comment by NayamAmarshe** [comment]
Hi, sorry for the delay. Currently busy with a few other things, I'll get back to you as soon as possible. Thank you!

**Comment by brocococonut** [comment]
You're all good!

**Comment by NayamAmarshe** [comment]
@brocococonut The PR is pretty sick! Thanks a lot and sorry for all the delay

**Pull request merged**
